image: Visual Studio 2022
version: 2024.817.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
clone_depth: 1
cache:
  - '%LOCALAPPDATA%\NuGet\v3-cache'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: 2024.817.0
  file_version: 2024.817.0
build_script:
- cmd: >-
    dotnet build osu.Desktop -c Release -r win-x64

    dotnet build osu.Desktop -c Release -r linux-x64

    dotnet build osu.Desktop -c Release -r linux-arm
test: off
artifacts:
- path: ./osu.Desktop/bin/Release/net8.0/win-x64
  name: osu-windows
- path: ./osu.Desktop/bin/Release/net8.0/linux-x64
  name: osu-linux-x64
- path: ./osu.Desktop/bin/Release/net8.0/linux-arm
  name: osu-linux-arm
deploy:
- provider: GitHub
  tag: 2024.817.0
  auth_token:
    secure: EEbZ2OGaIPcjhGpQGzfE80TbrG14UiTPGNnQjMIKD5wzrYPQ4Kyhb3qLzMNahL1I
  repository: PercyDan54/osu
  artifact: osu-windows, osu-linux-x64, osu-linux-arm
